=== Gradiant/grad-ssikit-vclib-android/src/test/resources/schemas/AmletCredential.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialStatus" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "birthDate" : {
          "type" : "string"
        },
        "birthPlace" : {
          "type" : "string"
        },
        "company" : {
          "type" : "object",
          "properties" : {
            "address" : {
              "type" : "string"
            },
            "email" : {
              "type" : "string"
            },
            "foundingDate" : {
              "type" : "string"
            },
            "hasInternationalActivity" : {
              "type" : "boolean"
            },
            "isRecipientOfPublicFunds" : {
              "type" : "boolean"
            },
            "isRiskSector" : {
              "type" : "boolean"
            },
            "name" : {
              "type" : "string"
            },
            "revenue" : {
              "type" : "string"
            },
            "ultimateBeneficialOwners" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "properties" : {
                  "address" : {
                    "type" : "string"
                  },
                  "birthDate" : {
                    "type" : "string"
                  },
                  "birthPlace" : {
                    "type" : "string"
                  },
                  "citizenship" : {
                    "type" : "string"
                  },
                  "familyName" : {
                    "type" : "string"
                  },
                  "givenName" : {
                    "type" : "string"
                  },
                  "isPep" : {
                    "type" : "boolean"
                  },
                  "taxID" : {
                    "type" : "string"
                  }
                },
                "additionalProperties" : false
              }
            },
            "vatId" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "execRappr" : {
          "type" : "string"
        },
        "familyName" : {
          "type" : "string"
        },
        "givenName" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "taxID" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== Gradiant/grad-ssikit-vclib-android/src/test/resources/serialized/AmletCredential.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "credentialSchema": {
    "id": "https://raw.githubusercontent.com/walt-id/waltid-ssikit-vclib/master/src/test/resources/schemas/AmletCredential.json",
    "type": "JsonSchemaValidator2018"
  },
  "credentialSubject": {
    "birthDate": "1995-05-03",
    "birthPlace": "Milan",
    "company": {
      "address": "VLE. BACCHIGLIONE 20, MILANO",
      "email": "info@mopso.it",
      "foundingDate": "2021-01-01",
      "hasInternationalActivity": true,
      "isRecipientOfPublicFunds": true,
      "isRiskSector": false,
      "name": "Mopso",
      "revenue": "10000",
      "ultimateBeneficialOwners": [{
        "address": "Milan, Italy",
        "birthDate": "1995-05-03",
        "birthPlace": "Milan",
        "citizenship": "Italian",
        "familyName": "Doe",
        "givenName": "Jane",
        "isPep": false,
        "taxID": "DOEJNA95M43Z330V"
      }],
      "vatId": "11717750969"
    },
    "execRappr": "LEGAL REPRESENTATIVE",
    "familyName": "Doe",
    "givenName": "Jane",
    "id": "did:ebsi:zukSNRQ7Umb2TzbRLNkTGX4#3bf09a67ac1348f4bfe35b7c7fc54fba",
    "taxID": "DOEJNA95M43Z330V"
  },
  "expirationDate": "2023-03-21T00:00:00Z",
  "id": "",
  "issued": "2022-03-21T00:00:00Z",
  "issuer": "did:ebsi:zkttgPyjddU8JqrkQ9aV5MW#6462224517f04e9d84ba1ea09c82e01c",
  "validFrom": "2022-03-21T00:00:00Z",
  "issuanceDate": "2022-03-21T00:00:00Z",
  "type": ["VerifiableCredential", "AmletCredential"]
}
