=== Gradiant/grad-ssikit-vclib-android/src/test/resources/schemas/GaiaxSelfDescription.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "dependsOn" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "description" : {
          "type" : "string"
        },
        "hasCertifications" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "hasMarketingImage" : {
          "type" : "string"
        },
        "hasName" : {
          "type" : "string"
        },
        "hasVersion" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "providedBy" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "utilizes" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== Gradiant/grad-ssikit-vclib-android/src/test/resources/serialized/GaiaxSelfDescription.json
{"@context" : ["https://www.w3.org/2018/credentials/v1"], "credentialSubject" : {"dependsOn" : ["Pilot004DataService"], "description" : "AIS demonstrates machine learning application use case.", "hasCertifications" : ["ISO_27001", "GDPR_Compliance"], "hasMarketingImage" : "https://www.data-infrastructure.eu/GAIAX/Redaktion/EN/Bilder/UseCases/ai-marketplace-for-product-development.jpg?__blob=normal", "hasName" : "AIS", "hasVersion" : "0.1.0", "id" : "Pilot004AIService", "providedBy" : "GAIA-X", "type" : "Service", "utilizes" : ["ExampleKubernetesService"]}, "id" : "did:ebsi-eth:00000001/credentials/1872", "issuanceDate" : "2020-08-24T14:13:44Z", "issuer" : "did:example:456", "type" : ["VerifiableCredential", "GaiaxSelfDescription"]}
