=== Gradiant/grad-ssikit-vclib-android/src/test/resources/schemas/GaiaxCredential.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "DNSpublicKey" : {
          "type" : "string"
        },
        "brandName" : {
          "type" : "string"
        },
        "commercialRegister" : {
          "type" : "object",
          "properties" : {
            "countryName" : {
              "type" : "string"
            },
            "locality" : {
              "type" : "string"
            },
            "organizationName" : {
              "type" : "string"
            },
            "organizationUnit" : {
              "type" : "string"
            },
            "postalCode" : {
              "type" : "string"
            },
            "streetAddress" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "corporateEmailAddress" : {
          "type" : "string"
        },
        "ethereumAddress" : {
          "type" : "object",
          "properties" : {
            "id" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "id" : {
          "type" : "string"
        },
        "individualContactLegal" : {
          "type" : "string"
        },
        "individualContactTechnical" : {
          "type" : "string"
        },
        "jurisdiction" : {
          "type" : "string"
        },
        "legalForm" : {
          "type" : "string"
        },
        "legalRegistrationNumber" : {
          "type" : "string"
        },
        "legallyBindingAddress" : {
          "type" : "object",
          "properties" : {
            "countryName" : {
              "type" : "string"
            },
            "locality" : {
              "type" : "string"
            },
            "postalCode" : {
              "type" : "string"
            },
            "streetAddress" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "legallyBindingName" : {
          "type" : "string"
        },
        "trustState" : {
          "type" : "string"
        },
        "webAddress" : {
          "type" : "object",
          "properties" : {
            "url" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== Gradiant/grad-ssikit-vclib-android/src/test/resources/serialized/GaiaxCredential.json
{"@context" : ["https://www.w3.org/2018/credentials/v1"], "credentialSubject" : {"DNSpublicKey" : "04:8B:CA:33:B1:A1:3A:69:E6:A2:1E:BE:CB:4E:DF:75:A9:70:8B:AA:51:83:AB:A1:B0:5A:35:20:3D:B4:29:09:AD:67:B4:12:19:3B:6A:B5:7C:12:3D:C4:CA:DD:A5:E0:DA:05:1E:5E:1A:4B:D1:F2:BA:8F:07:4D:C7:B6:AA:23:46", "brandName" : "deltaDAO", "commercialRegister" : {"countryName" : "Germany", "locality" : "Hamburg", "organizationName" : "Amtsgericht Hamburg (-Mitte)", "organizationUnit" : "Registergericht", "postalCode" : "20355", "streetAddress" : "Caffamacherreihe 20"}, "corporateEmailAddress" : "contact@delta-dao.com", "ethereumAddress" : {"id" : "0x4C84a36fCDb7Bc750294A7f3B5ad5CA8F74C4A52"}, "id" : "did:key:dummy", "individualContactLegal" : "legal@delta-dao.com", "individualContactTechnical" : "support@delta-dao.com", "jurisdiction" : "Germany", "legalForm" : "Stock Company", "legalRegistrationNumber" : "HRB 170364", "legallyBindingAddress" : {"countryName" : "Germany", "locality" : "Hamburg", "postalCode" : "22303", "streetAddress" : "Geibelstr. 46B"}, "legallyBindingName" : "deltaDAO AG", "trustState" : "trusted", "webAddress" : {"url" : "https://www.delta-dao.com/"}}, "id" : "did:ebsi-eth:00000001/credentials/1872", "issuanceDate" : "2020-08-24T14:13:44Z", "issuer" : "did:example:456", "type" : ["VerifiableCredential", "GaiaxCredential"]}
