=== Gradiant/grad-ssikit-vclib-android/src/test/resources/schemas/PeerReview.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "completedDate" : {
          "type" : "string"
        },
        "groupingKey" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "measurements" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "properties" : {
              "indicators" : {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "properties" : {
                    "category" : {
                      "type" : "string"
                    },
                    "name" : {
                      "type" : "string"
                    },
                    "type" : {
                      "type" : "string"
                    }
                  },
                  "additionalProperties" : false
                }
              },
              "name" : {
                "type" : "string"
              },
              "numberValue" : {
                "type" : "integer"
              },
              "scale" : {
                "type" : "string"
              },
              "type" : {
                "type" : "string"
              }
            },
            "additionalProperties" : false
          }
        },
        "name" : {
          "type" : "string"
        },
        "providerName" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "type" ],
  "additionalProperties" : false
}

=== Gradiant/grad-ssikit-vclib-android/src/test/resources/serialized/PeerReview.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "credentialSchema": {
    "id": "https://raw.githubusercontent.com/walt-id/waltid-ssikit-vclib/master/src/test/resources/serialized/PeerReview.json",
    "type": "JsonSchemaValidator2018"
  },
  "credentialSubject": {
    "completedDate": "2021-08-31T00:00:00Z",
    "groupingKey": "c4235de3-e35b-4a53-ac46-f62c2b222441",
    "id": "identity#verifiableID",
    "measurements": [{
      "indicators": [{
        "category": "SKILL",
        "name": "Coaching",
        "type": "People Skills"
      }],
      "name": "Coaching",
      "numberValue": 87,
      "scale": "PERCENTAGE",
      "type": "People Skills"
    }],
    "name": "WorkPi Peer Review",
    "providerName": "WorkPi",
    "type": "Assessment"
  },
  "id": "identity#PeerReview#3add94f4-28ec-42a1-8704-4e4aa51006b4",
  "issued": "2021-08-31T00:00:00Z",
  "issuer": "did:example:456",
  "validFrom": "2021-08-31T00:00:00Z",
  "issuanceDate": "2021-08-31T00:00:00Z",
  "type": ["VerifiableCredential", "PeerReview"]
}
