=== Gradiant/grad-ssikit-vclib-android/src/test/resources/schemas/PermanentResidentCard.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "birthDate" : {
          "type" : "string"
        },
        "givenName" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== Gradiant/grad-ssikit-vclib-android/src/test/resources/serialized/PermanentResidentCard.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1"
  ],
  "credentialSubject": {
    "birthDate": "1958-08-17",
    "givenName": "JOHN",
    "id": "did:example:123",
    "type": [
      "PermanentResident",
      "Person"
    ]
  },
  "issuer": "did:example:456",
  "proof": {
    "created": "2020-04-22T10:37:22Z",
    "jws": "eyJjcml0IjpbImI2NCJdLCJiNjQiOmZhbHNlLCJhbGciOiJFZERTQSJ9..BhWew0x-txcroGjgdtK-yBCqoetg9DD9SgV4245TmXJi-PmqFzux6Cwaph0r-mbqzlE17yLebjfqbRT275U1AA",
    "proofPurpose": "assertionMethod",
    "type": "Ed25519Signature2018",
    "verificationMethod": "did:example:456#key-1"
  },
  "type": [
    "VerifiableCredential",
    "PermanentResidentCard"
  ]
}
